server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TimeBank-Sparta/Config.git
          clone-on-start: true
          username: 20152842
          password: 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

# ???/???? ??? ??? ??
encrypt:
  key: mySecretEncryptionKey123!