services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - gateway-blue
      - gateway-green
    networks:
      - msanet

  config-server:
    image: namgyu967/config-server:${TAG}
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - .env
    depends_on:
      - eureka-server
    networks:
      - msanet

  eureka-server:
    image: namgyu967/eureka-server:${TAG}
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8761
    networks:
      - msanet

  # 1) Blue Gateway
  gateway-blue:
    image: namgyu967/gateway-service:${TAG}
    container_name: gateway-blue
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - msanet

  # 2) Green Gateway
  gateway-green:
    image: namgyu967/gateway-service:${TAG}
    container_name: gateway-green
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - msanet

  help-service:
    image: namgyu967/help-service:${TAG}
    container_name: help-service
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - help-mysql
      - zookeeper
      - kafka
      - gateway-service
    entrypoint: sh -c "./wait-for-it.sh gateway-service:8080 --timeout=60 --strict -- java -jar help-service.jar"
    networks:
      - msanet

  notification-service:
    image: namgyu967/notification-service:${TAG}
    container_name: notification-service
    restart: always
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - notification-mysql
      - gateway-service
    entrypoint: sh -c "./wait-for-it.sh gateway-service:8080 --timeout=60 --strict -- java -jar help-service.jar"

    networks:
      - msanet

  review-service:
    image: namgyu967/review-service:${TAG}
    container_name: review-service
    restart: always
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - review-mysql
      - gateway-service
    entrypoint: sh -c "./wait-for-it.sh gateway-service:8080 --timeout=60 --strict -- java -jar help-service.jar"
    networks:
      - msanet

  point-service:
    image: namgyu967/point-service:${TAG}
    container_name: point-service
    restart: always
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - point-mysql
      - gateway-service
      - zookeeper
      - kafka
    entrypoint: sh -c "./wait-for-it.sh gateway-service:8080 --timeout=60 --strict -- java -jar help-service.jar"
    networks:
      - msanet

  user-service:
    image: namgyu967/user-service:${TAG}
    container_name: user-service
    restart: always
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - user-mysql
      - gateway-service
    entrypoint: sh -c "./wait-for-it.sh gateway-service:8080 --timeout=60 --strict -- java -jar help-service.jar"
    networks:
      - msanet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - msanet

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
      - config-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - msanet

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "9093:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - msanet

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - msanet

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - msanet

  help-mysql:
    image: mysql:8
    container_name: help-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: help_db
    ports:
      - "3307:3306"
    volumes:
      - help_mysql_data:/var/lib/mysql
    networks:
      - msanet

  notification-mysql:
    restart: always
    image: mysql:8
    container_name: notification-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: notification_db
    ports:
      - "3308:3306"
    volumes:
      - notification_mysql_data:/var/lib/mysql
    networks:
      - msanet

  review-mysql:
    restart: always
    image: mysql:8
    container_name: review-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: review_db
    ports:
      - "3309:3306"
    volumes:
      - review_mysql_data:/var/lib/mysql
    networks:
      - msanet

  point-mysql:
    restart: always
    image: mysql:8
    container_name: point-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: point_db
    ports:
      - "3310:3306"
    volumes:
      - point_mysql_data:/var/lib/mysql
    networks:
      - msanet

  user-mysql:
    restart: always
    image: mysql:8
    container_name: user-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: user_db
    ports:
      - "3311:3306"
    volumes:
      - user_mysql_data:/var/lib/mysql
    networks:
      - msanet

networks:
  msanet:
    driver: bridge
    external: true

volumes:
  help_mysql_data:
  notification_mysql_data:
  review_mysql_data:
  point_mysql_data:
  user_mysql_data:
