### 게시글 생성
POST http://localhost:19092/api/help_requests
Content-Type: application/json

{
  "title": "청소인원모집2",
  "content": "우리집 청소 부탁드립니다.",
  "address": "서울특별시 강남구 테헤란로 152",
  "scheduledAt": "2025-04-07T15:30:00",
  "requiredTime": 2,
  "requestedPoint": 120,
  "recruitmentCount": 5,
  "postStatus": "OPEN"
}

### 지원자 생성
POST http://localhost:19092/api/helpers
Content-Type: application/json

{
  "helpRequestId": 3,
  "userId": 3
}

### 게시글 생성
POST http://localhost:19092/api/tradings
Content-Type: application/json

{
  "helpRequestId": 1,
  "requesterId": 5,
  "helperId": 2,
  "actualPoints": 120
}

