### 거래내역 생성
POST http://localhost:19092/api/v1/help-tradings
Content-Type: application/json

{
  "helpRequestId": 1,
  "requesterId": 5,
  "helperId": 2,
  "actualPoints": 120
}

### 게시글 기준 거래내역 조회
GET http://localhost:19092/api/v1/help-tradings/1?page=0&size=10

### 거래내역 삭제
DELETE http://localhost:19092/api/v1/help-tradings/1