server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TimeBank-Sparta/Config.git
          clone-on-start: true
          username: "{cipher}f6f2c9f6f0ddd92e3e25a31f8f6b632e5ef9e3ec2ae291c226b4022b78e2e140"
          password: "{cipher}99162c5eb7ae281d76c137dc11fe7026379b86494f2d5f990cee8dfeb8dfedea6b7dc33164bc48ec6a6a6d74bccb2683feb7cb22bec69cafa6aa8d31ccc04790"
  application:
    name: config-server
encrypt:
  #  key: ${SPRING_CLOUD_CONFIG_SERVER_ENCRYPT_KEY}
  key: timebank

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"