name: Deploy to EC2 (Blue-Green)

on:
  push:
    branches:
      - main  # main에 push (develop에서 main으로 병합될 때만 실행)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Define Tag
      id: define_tag
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Build and Push Docker Images
      run: |
        services="gateway-service help-service notification-service review-service point-service user-service config-server eureka-server"
        for service in $services; do
          docker build -t namgyu967/$service:${{ env.TAG }} -f $service/Dockerfile .
          docker push namgyu967/$service:${{ env.TAG }}
        done

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          echo "TAG=${{ env.TAG }}" > .env-tag
          source .env-tag

          docker-compose pull
          docker-compose -f docker-compose.yml up -d

          docker image prune -af

    # # ✅ 추가 작업 (선택 사항): 배포 후 main의 내용을 develop에 반영
    # - name: Merge main into develop
    #   run: |
    #     git config user.name "github-actions[bot]"
    #     git config user.email "github-actions[bot]@users.noreply.github.com"
    #     git checkout develop
    #     git merge --no-ff main -m "Auto-merge main into develop [skip ci]"
    #     git push origin develop
