name: Deploy to EC2 (Blue-Green)

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SLACK_DEV_WEBHOOK_URL: ${{ secrets.SLACK_DEV_WEBHOOK_URL }}
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}
      SERVICES: "gateway-service help-service notification-service review-service point-service user-service config-server eureka-server"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Define TAG
      id: define_tag
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Detect Changed Services
      id: detect_services
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        if echo "$CHANGED_FILES" | grep -Eq '(^build.gradle|^settings.gradle|^gradlew|^build.gradle.kts|^common/)'; then
          echo "CHANGED=ALL" >> $GITHUB_ENV
        else
          CHANGED=$(echo "$CHANGED_FILES" \
            | grep -E '^(gateway-service|help-service|notification-service|review-service|point-service|user-service|config-server|eureka-server)/' \
            | awk -F/ '{print $1}' | sort -u | xargs)
          echo "CHANGED=$CHANGED" >> $GITHUB_ENV
        fi

    - name: Check EC2 for Existing Containers
      id: remote_check
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          COUNT=$(docker ps \
            --filter "name=gateway-blue" --filter "name=gateway-green" \
            --filter "name=help-service" --filter "name=notification-service" \
            --filter "name=review-service" --filter "name=point-service" \
            --filter "name=user-service" --filter "name=config-server" \
            --filter "name=eureka-server" \
            --format '{{.Names}}' \
            | wc -l)
          echo "EXISTING_COUNT=$COUNT" >> $GITHUB_ENV

    - name: Cancel if No Changes & Not Initial Deploy
      run: |
        if [ "${CHANGED}" = "" ] && [ "${EXISTING_COUNT}" -gt 2 ]; then
          echo "No changes and not initial deploy. Skipping."
          exit 0
        fi

    - name: Build & Push Changed Services
      run: |
        if [ "${CHANGED}" = "ALL" ]; then
          TARGETS=($SERVICES)
        else
          TARGETS=($CHANGED)
        fi
        for service in "${TARGETS[@]}"; do
          docker build -t namgyu967/$service:${TAG} -f $service/Dockerfile .
          docker push namgyu967/$service:${TAG}
        done

    - name: Deploy via SSH (Blue-Green Gateway + Others)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/timebank

          # Blue-Green toggle
          if docker ps --filter name=gateway-blue --filter status=running | grep -q gateway-blue; then
            NEW=green; OLD=blue
          else
            NEW=blue; OLD=green
          fi

          # Deploy new gateway
          docker pull namgyu967/gateway-service:${TAG}-$NEW
          docker stop gateway-$OLD || true
          docker rm gateway-$OLD || true
          docker run -d --name gateway-$NEW --network msanet -e SERVER_PORT=8080 namgyu967/gateway-service:${TAG}-$NEW

          # Update Nginx upstream
          sed -i "s/server gateway-$OLD:8080;/server gateway-$NEW:8080;/" nginx-conf/gw.conf
          docker exec nginx nginx -s reload

          # Deploy other changed services
          if [ "${CHANGED}" = "ALL" ]; then
            TARGETS=($SERVICES)
          else
            TARGETS=($CHANGED)
          fi
          for service in "${TARGETS[@]}"; do
            if [ "$service" != "gateway-service" ]; then
              docker-compose pull $service
              docker-compose up -d $service
            fi
          done

          docker image prune -af

    - name: Health Check & Summarize
      id: health
      run: |
        SUCCESS=""
        FAILED=""
        BASE="http://${{ secrets.EC2_PUBLIC_IP }}:8080"
        for svc in ${{ env.CHANGED }}; do
          ENDPOINT="$BASE"
          if [ "$svc" != "gateway-service" ]; then
            ENDPOINT="$BASE/$svc"
          fi
          for i in {1..10}; do
            sleep 5
            code=$(curl -s -o /dev/null -w "%{http_code}" "$ENDPOINT/actuator/health")
            if [ "$code" = "200" ]; then
              SUCCESS="$SUCCESS $svc"
              break
            fi
            if [ "$i" -eq 10 ]; then
              FAILED="$FAILED $svc"
            fi
          done
        done
        echo "SUCCESS=$SUCCESS" >> $GITHUB_ENV
        echo "FAILED=$FAILED" >> $GITHUB_ENV

    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ${{ toJson(join(
              [
                github.ref == 'refs/heads/main'
                  ? ":white_check_mark: *[PROD]* 배포 성공!"
                  : ":white_check_mark: *[DEV]* 배포 성공!",
                "> 변경된 서비스:${CHANGED:- none}",
                "> 정상:${SUCCESS:- none}",
                "> 실패:${FAILED:- none}",
                "> 태그:${TAG}",
                "> Gateway: http://${{ secrets.EC2_PUBLIC_IP }}"
              ], "\n"
            )) }}
          }
      env:
        SLACK_WEBHOOK_URL: ${{ github.ref == 'refs/heads/main' && secrets.SLACK_PROD_WEBHOOK_URL || secrets.SLACK_DEV_WEBHOOK_URL }}

    - name: Slack Notification (Failure)
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ${{ toJson(join(
              [
                github.ref == 'refs/heads/main'
                  ? ":x: *[PROD]* 배포 실패!*"
                  : ":x: *[DEV]* 배포 실패!*",
                "> 에러 로그를 확인해주세요."
              ], "\n"
            )) }}
          }
      env:
        SLACK_WEBHOOK_URL: ${{ github.ref == 'refs/heads/main' && secrets.SLACK_PROD_WEBHOOK_URL || secrets.SLACK_DEV_WEBHOOK_URL }}
